proxmox_api_url  = "https://10.229.0.2:8006/api2/json"
proxmox_user     = "s.lefebvre@LAB-LYON"
proxmox_password = "JLSZR716"
proxmox_node     = "proxmox-02"
#proxmox_template = "ubuntu-22.04-cloud"
ssh_public_key   = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLRHn9GRW9GQHZ7qSbLUbOcw0INQsUPDP0DtoBPyS3b samue@sam"
storage_pool     = "local-lvm"
domain           = "acme.local"
