all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_ed25519

  children:

    # ── VLAN 20 — SERVERS ────────────────────────────────────────────────────
    identity:
      hosts:
        freeipa:
          ansible_host: 10.20.0.10
          ansible_user: root          # Rocky Linux 9 VM (Proxmox)

    database:
      hosts:
        postgresql:
          ansible_host: 10.20.0.20
          ansible_user: root          # Debian 12 LXC

    monitoring:
      hosts:
        prometheus:
          ansible_host: 10.20.0.40
          ansible_user: root          # Debian 12 LXC
        grafana:
          ansible_host: 10.20.0.41
          ansible_user: root          # Ubuntu 22.04 LXC

    logging:
      hosts:
        loki:
          ansible_host: 10.20.0.42
          ansible_user: root          # Debian 12 LXC

    backup:
      hosts:
        bareos:
          ansible_host: 10.20.0.50
          ansible_user: root          # Ubuntu 22.04 LXC

    # ── VLAN 30 — DMZ ────────────────────────────────────────────────────────
    proxy:
      hosts:
        traefik:
          ansible_host: 10.30.0.10
          ansible_user: root          # Debian 12 LXC

    # ── Groupes logiques ─────────────────────────────────────────────────────
    servers:
      children:
        identity:
        database:
        monitoring:
        logging:
        backup:

    dmz:
      children:
        proxy:

    # ── Postes d'administration ───────────────────────────────────────────────
    admin_workstations:
      hosts:
        admin-01:
          ansible_host: 10.10.0.15
          ansible_user: root
        admin-02:
          ansible_host: 10.10.0.16
          ansible_user: root

    # ── Bareos ───────────────────────────────────────────────────────────────
    bareos_servers:
      hosts:
        bareos:
          ansible_host: 10.20.0.50
          ansible_user: root

    bareos_clients:
      hosts:
        postgresql:
          ansible_host: 10.20.0.20
          ansible_user: root          # Debian 12
