all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    identity:
      hosts:
        freeipa:
          ansible_host: 192.168.10.10
          ansible_user: ubuntu

    database:
      hosts:
        postgresql:
          ansible_host: 192.168.10.20
          ansible_user: ubuntu

    monitoring:
      hosts:
        prometheus_grafana:
          ansible_host: 192.168.10.30
          ansible_user: ubuntu

    logging:
      hosts:
        loki:
          ansible_host: 192.168.10.40
          ansible_user: ubuntu

    backup:
      hosts:
        bareos:
          ansible_host: 192.168.10.50
          ansible_user: ubuntu

    proxy:
      hosts:
        traefik:
          ansible_host: 192.168.20.10
          ansible_user: ubuntu

    app:
      hosts:
        flask_app:
          ansible_host: 192.168.20.20
          ansible_user: ubuntu

    servers:
      children:
        identity:
        database:
        monitoring:
        logging:
        backup:

    dmz:
      children:
        proxy:
        app:
