---
- name: Ajouter le dépôt Grafana
  block:
    - name: Clé GPG Grafana
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Dépôt Grafana
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana
  tags: install

- name: Installer Grafana
  apt:
    name: grafana
    state: present
    update_cache: true
  tags: install

- name: Configurer grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: "0640"
    owner: root
    group: grafana
  notify: restart grafana
  tags: configure

- name: Déployer les datasources (Prometheus + Loki)
  template:
    src: "datasources.yml.j2"
    dest: "/etc/grafana/provisioning/datasources/acme.yml"
    mode: "0640"
    owner: root
    group: grafana
  notify: restart grafana
  tags: configure

- name: Déployer les dashboards provisionnés
  copy:
    src: "{{ playbook_dir }}/../monitoring/grafana/dashboards/"
    dest: /var/lib/grafana/dashboards/
    owner: grafana
    group: grafana
    mode: "0644"
  notify: restart grafana
  tags: configure

- name: Config provider de dashboards
  template:
    src: dashboards-provider.yml.j2
    dest: /etc/grafana/provisioning/dashboards/acme.yml
    mode: "0640"
    owner: root
    group: grafana
  notify: restart grafana
  tags: configure

- name: Démarrer Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true
  tags: configure
