---
# freeipa.ansible_freeipa.ipauser — collection officielle Red Hat

- name: Créer l'utilisateur alice (admin)
  freeipa.ansible_freeipa.ipauser:
    ipaadmin_password: "{{ freeipa_admin_password }}"
    name: alice
    first: Alice
    last: Admin
    mail: alice@{{ freeipa_domain }}
    password: "Admin1234!"
    update_password: on_create
    groups:
      - acme-admins
      - acme-users
    state: present

- name: Créer l'utilisateur bob (utilisateur standard)
  freeipa.ansible_freeipa.ipauser:
    ipaadmin_password: "{{ freeipa_admin_password }}"
    name: bob
    first: Bob
    last: User
    mail: bob@{{ freeipa_domain }}
    password: "User1234!"
    update_password: on_create
    groups:
      - acme-users
    state: present

- name: Créer l'utilisateur carol (lecture seule)
  freeipa.ansible_freeipa.ipauser:
    ipaadmin_password: "{{ freeipa_admin_password }}"
    name: carol
    first: Carol
    last: Readonly
    mail: carol@{{ freeipa_domain }}
    password: "Read1234!"
    update_password: on_create
    groups:
      - acme-readonly
    state: present
