---
- name: Bareos — Serveur de sauvegarde
  hosts: bareos_servers
  become: true
  vars:
    bareos_dir_name: bareos-dir
    bareos_sd_name: bareos-sd
    bareos_director_address: "{{ ansible_host }}"
    bareos_fd_password: "CHANGE_ME_FD_PASSWORD"

    bareos_dir_conf_path: /etc/bareos/bareos-dir.d
    bareos_manual_scripts_path: /usr/local/bin

    bareos_schedule_name: WeeklyCycle
    bareos_full_pool_name: FullPool
    bareos_inc_pool_name: IncPool

    bareos_clients:
      - name: postgres-fd
        address: 10.20.0.20
        password: "CHANGE_ME_FD_PASSWORD"
        backup_paths:
          - /var/backups/postgresql
      - name: freeipa-fd
        address: 10.20.0.10
        password: "CHANGE_ME_FD_PASSWORD"
        backup_paths:
          - /etc/ipa
          - /var/lib/ipa

  roles:
    - bareos_server

- name: Bareos — Clients (File Daemon)
  hosts: bareos_clients
  become: true
  vars:
    bareos_fd_password: "CHANGE_ME_FD_PASSWORD"
    bareos_fd_conf_path: /etc/bareos/bareos-fd.d
    bareos_director_name: bareos-dir
  roles:
    - bareos_client
